matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8
    - os: linux
      language: android
      jdk: oraclejdk8
      sudo: required
      android:
        components:
          - platform-tools
          - tools
          - tools/bin
          - build-tools-25.0.1
          - android-25
          - sys-img-armeabi-v7a-android-25
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services

cache:
  directories:
    - $HOME/.nvm
    - $HOME/.npm
    - $HOME/.cocoapods
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - example/node_modules

before_cache: .travis/before-cache.sh
before_install:
  - chmod +x .travis/before-install.sh
  - chmod +x .travis/before-ci.sh
  - chmod +x .travis/install.sh
  - chmod +x .travis/ci.sh
  - . .travis/before-install.sh
install: .travis/install.sh
script: .travis/ci.sh

